---
title: "Lemonade Analysis"
author: "Sophie Beiers"
date: "3/23/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Documents/GitHub/Lemonade/docs")
library(tidyverse)
library(tm)
library(Matrix)
library(tidytext)
library(ggridges)
library(wordcloud)
library(ggrepel)
library(scales)
```

## Data
```{r}
txts <- VCorpus(DirSource(directory = "/Users/sophiebeiers/Documents/GitHub/Lemonade/data/txts"))

txts.df <- read_csv("../data/chps.csv")

meta(txts, type="local", tag="title") <- txts.df$song_title
meta(txts, type="local", tag="chapter")   <- txts.df$chapter

exceptions   <- c("i", "we", "we're", "we've", "we'd", "us", "they", "them", "they've", "they're", "he", "she", "she'll", "she'd", "she's", "you", "you're", "you've", "your","him", "my", "mine", "her", "hers", "his", "him", "sorry")

exceptions2 <- c("sorry", "said")

my_stopwords <- setdiff(stopwords("en"), exceptions)
reg_stopwords <- setdiff(stopwords("en"), exceptions2)

# prepping data
corpus <- tm_map(txts, content_transformer(tolower))
corpus <- tm_map(corpus, stripWhitespace)
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, my_stopwords)


# document term matrix
doctm <- DocumentTermMatrix(corpus) # create DocumentTermMatrix 
doctm_m <- as.matrix(doctm)

# term document matrix
doc_tdm <- TermDocumentMatrix(corpus)
doc_tdm_m <- as.matrix(doc_tdm)

# tidy object
doc_td <- tidy(doc_tdm)

# merge information
meta <- as_data_frame(str_split_fixed(doc_td$document, "_", n = 3))
colnames(meta) <- c("Order", "Song_title", "Chapter")
doc_td <- as_data_frame(cbind(doc_td, meta))
doc_td$Chapter <- str_sub(doc_td$Chapter, 1, str_length(doc_td$Chapter)-4)

# bag of words
words <- txts.df %>%
  unnest_tokens(word, lyrics) %>% 
  mutate(row = row_number())
```

## Analysis
### Common Words
```{r}
topwords <- doc_td %>% 
  #anti_join(stop_words, by= c("term" = "word")) %>% 
  filter(!(term %in% reg_stopwords)) %>% 
  group_by(term) %>%
  summarise(n = sum(count)) %>%
  top_n(n = 20, wt = n)  %>%
  ungroup() %>%
  mutate(term = reorder(term, n))


ggplot(data = topwords, aes(term, n)) + 
  geom_bar(stat = "identity", fill = "#ffcc00") + 
  geom_text(aes(label = term, x=term, y = 1), hjust = 0,
            size = 4, color = "#b35900") +
  geom_text(aes(label= n, x=term, y = n-1), hjust = 1, color= 'white') +
  xlab(NULL) +coord_flip() + theme_light() + 
  theme(axis.title = element_blank(), 
        axis.text = element_blank(), 
        axis.ticks = element_blank()) +
  labs(x = '', title = "Most Frequent Words in Beyonce's Lemonade", 
       subtitle = "Number of times word appeared in album")
```

#### Common Words by Chapter
```{r}
# order chapters and songs 
doc_td$Song_title[doc_td$Chapter == "Emptiness"] <- "6 Inch"
doc_td$Song_title[doc_td$Chapter == "Anger"] <- "Don't Hurt Yourself"
doc_td$Song_title2 <- paste(doc_td$Order, sep = '. ', doc_td$Song_title)
doc_td$Song_title <- factor(doc_td$Song_title, levels = c("Pray You Catch Me", "Hold Up", "Don't Hurt Yourself", "Sorry", "6 Inch", "Daddy Lessons", "Love Drought", "Sand Castles", "Forward", "Freedom", "All Night"))
doc_td$Song_title2 <- factor(doc_td$Song_title2, levels = c("1. Pray You Catch Me", "2. Hold Up", "3. Don't Hurt Yourself", "4. Sorry", "5. 6 Inch", "6. Daddy Lessons", "7. Love Drought", "8. Sand Castles", "9. Forward", "10. Freedom", "11. All Night"))
doc_td$Chapter <- factor(doc_td$Chapter, levels = c("Intuition", "Denial", "Anger", "Apathy", "Emptiness", "Accountability", "Reformation", "Forgiveness", "Ressurection", "Hope", "Redemption"))

topwords_song <- doc_td %>%
  filter(!(term %in% reg_stopwords)) %>% 
  arrange_(~ desc(count)) %>%
  group_by_(~ Song_title2) %>%
  slice(1:10) %>% 
  select(Song_title2, term, count)


ggplot(data = topwords_song, aes(reorder(term, count), count)) + 
  geom_bar(stat = "identity", fill = "#ffcc00") + 
  coord_flip() + theme_light() + 
  theme(axis.title = element_blank(), 
        axis.text.x =  element_blank(), 
        axis.ticks = element_blank()) +
  labs(x = '', 
       title = "Most Frequent Words in Beyonce's Lemonade", 
       subtitle = "Number of times word appeared in each song") +
  facet_wrap(~Song_title2, scales = "free_y") +
  theme(strip.text = element_text(size=8, color = 'black'),  
        strip.background = element_blank()) 

```

### Correlation
```{r, warning = FALSE}
cor(doc_tdm_m)
```

### TF - IDF
```{r}
# tf_idf
doc_tf_idf <-  doc_td %>%
                bind_tf_idf(term, document, count) %>%  
                arrange(desc(tf_idf))

doc_tf_idf %>% 
  filter(!(term %in% c("can","said"))) %>% 
  arrange_(~ desc(tf_idf)) %>% 
  group_by(Song_title2) %>% 
  slice(1:5) %>% 
ggplot(aes(x = reorder(term, desc(-tf_idf)), y = tf_idf)) +
  geom_bar(stat = "identity", fill = "#ffcc00") + coord_flip() +
  facet_wrap(~ Song_title2, scales="free_y") + 
  theme(axis.title = element_blank(), 
        axis.text.x =  element_blank(), 
        axis.ticks = element_blank()) +
  labs(x = '', y = '', title = "Most Important & Distinct Words Per Song") +
  theme_light() +
  theme(strip.text = element_text(size=8, color = 'black'),  
        strip.background = element_blank()) 
```
```{r}
# need to reorder
doc_td %>% 
  group_by(Song_title) %>% 
  mutate(unq_wrds = length(term)) %>% 
  select(Song_title, unq_wrds) %>% 
  unique() %>% 
ggplot(aes(x = reorder(Song_title, unq_wrds), y = unq_wrds)) +
         geom_segment(aes(x = Song_title, y = 0, xend = Song_title, yend = unq_wrds),
                          color = "#ffcc00", size = .5) +
         geom_point(size = 7, color = "#ffcc00") +
         geom_text(aes(label = unq_wrds), color = "black", size = 3, check_overlap = TRUE) +
         labs(x = "", y = "", title = "Number of Unique Words Per Song") +
         theme_light() +
         coord_flip() +
         theme(legend.position="none") +
         theme(
               axis.text.x =  element_blank(), 
               axis.ticks = element_blank()) 
  

```

### He/She
```{r}
# words set up
pronouns <- c("i", "we", "us", "they", "them", "he", "she", "shes", "you", "him", "her", "hers", "my", "mine")
fem_wrds <- c("her", "hers", "she","shes", "hers", "woman", "women", "girl", "girls", "mother", "i", "daughter", "daughters", "sister", "sisters", "momma", "Becky", "wife", "herself")
male_wrds <- c("he", "his", "hes", "man", "men", "mans", "boy", "boys", "daddy", "son", "sons", "brother", "brothers", "father")
together_wrds <- c("we", "us", "together")
you_wrds <- c("you", "your", "youre")
i_words <- c("i", "im", "me", "my")

# gender analysis 
shehe_song <- doc_td %>%
  filter((term %in% fem_wrds|term %in% male_wrds)) %>% 
  arrange_(~ desc(count)) %>%
  group_by_(~ Song_title) %>%
  select(Song_title, term, count)

shehe_song$male <- ifelse(shehe_song$term %in% male_wrds, -(shehe_song$count), 0)
shehe_song$female <- ifelse(shehe_song$term %in% fem_wrds, shehe_song$count, 0)
shehe_song$gender <- shehe_song$female + shehe_song$male

shehe_song <- shehe_song %>% 
  dplyr::group_by(Song_title) %>% 
  dplyr::mutate(gender2 = sum(gender))
shehe_song <- shehe_song %>% 
  dplyr::group_by(Song_title) %>% 
  dplyr::mutate(female2 = sum(female), male2 = sum(male))
shehe_song$gendertot <- ifelse(shehe_song$gender2 > 0, "female", "male")
shehe_song$gendertot <- factor(shehe_song$gendertot, levels = c("female", "male"))

# visualization 
ggplot(shehe_song, aes(x = Song_title, y = gender2)) +
  geom_segment(data = filter(shehe_song, male2 < 0),
               aes(x = Song_title, y = 0, 
                   xend = Song_title, yend = male2, color = "Words about Males"), 
               inherit.aes = FALSE, 
               arrow = arrow(length = unit(0.1, "inches"), ends = "last")) +
  geom_segment(data = filter(shehe_song, female2 > 1),
               aes(x = Song_title, y = 0, xend = Song_title, 
                   yend = female2, color = "Words about Females"),
               inherit.aes = FALSE,
               arrow = arrow(length = unit(0.1, "inches"), ends = "last")) +
  scale_color_manual(values=c("#ffcc00","#99ff33"), name = "") +
  coord_flip() +
  theme_light() +
  labs(x = '', y = '', title = 'He/She in Lemonade Songs', 
       caption = "(number of female or male pronouns used in each song) ") +
  theme(legend.position="top") +
  theme(axis.ticks = element_blank())
```

#### Bigrams
```{r}
# she/he bigrams 
bigrams <- txts.df %>%
  unnest_tokens(bigram, lyrics, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word1", "word2"), sep = " ")

she_bigram <- bigrams %>% 
  filter(word1 %in% fem_wrds) %>% 
  count(word2, sort = TRUE)

she_bigram_rev <- bigrams %>% 
  filter(word2 %in% fem_wrds) %>% 
  count(word1, sort = TRUE)

he_bigram <- bigrams %>% 
  filter(word1 %in% male_wrds) %>% 
  count(word2, sort = TRUE) %>% 
  slice(1:10)

he_bigram_rev <- bigrams %>% 
  filter(word2 %in% male_wrds) %>% 
  count(word1, sort = TRUE)

ggplot(data = he_bigram, aes(x = reorder(word2, desc(-n)), y = n)) +
  geom_bar(stat = "identity", fill = "#ffcc00") + coord_flip() +
  theme(axis.title = element_blank(), 
        axis.text.x =  element_blank(), 
        axis.ticks = element_blank()) +
  labs(x = '', y = '', title = "Most Common Words Before 'He'\n") +
  theme_light() +
  theme(strip.text = element_text(size=8, color = 'black'),  
        strip.background = element_blank()) 
```

```{r}
# change words so any fem words become "she" and any male words become "he"
bigrams$word1 <- ifelse(bigrams$word1 %in% male_wrds, "he", bigrams$word1)
bigrams$word1 <- ifelse(bigrams$word1 %in% fem_wrds, "she", bigrams$word1)

# code borrowed from: https://www.r-bloggers.com/a-tidytext-analysis-of-the-weinstein-effect/
he_she_bigram <- bigrams %>%
  filter(word1 %in% c("he", "she"))

he_she_bigram <- he_she_bigram %>%
  count(word1, word2) %>%
  spread(word1, n, fill = 0) %>%
  mutate(total = he + she,
         he = (he + 1) / sum(he + 1),
         she = (she + 1) / sum(she + 1),
         log.ratio = log2(she / he),
         abs.ratio = abs(log.ratio)) %>%
  arrange(desc(log.ratio))

he_she_bigram %>%
  group_by(direction = ifelse(log.ratio > 0, 'More "she"', "More 'he'")) %>%
  top_n(10, abs.ratio) %>%
  ungroup() %>%
  mutate(word2 = reorder(word2, log.ratio)) %>%
  ggplot(aes(word2, log.ratio, fill = direction)) +
  geom_col() +
  coord_flip() +
  labs(x = "",
       y = 'Relative appearance after "she" compared to "he"',
       fill = "",
       title = "title",
       subtitle = "") +
  scale_y_continuous(labels = c("8X", "6X", "4X", "2X", "Same", "2X", "4X", "6X", "8X"),
                     breaks = seq(-4, 4)) +
  guides(fill = guide_legend(reverse = TRUE)) +
  expand_limits(y = c(-4, 4)) +
  theme_light()

```
```{r}
he_she_bigram %>%
  top_n(10, abs.ratio) %>%
  ggplot(aes(total, log.ratio)) +
  geom_point() +
  geom_vline(xintercept = 5, color = "NA") +
  geom_hline(yintercept = 0, color = "red") +
  scale_x_log10(breaks = c(10, 100, 1000)) +
  geom_text_repel(aes(label = word2), segment.alpha = .1, force = 2) +
  scale_y_continuous(breaks = seq(-4, 4),
                     labels = c('8X "he"', '6X "he"', '4X "he"', '2X "he"', "Same",
                                '2X "she"', '4X "she"', '6X "she"', '8X "she"')) +
  labs(x = 'Total uses after "he" or "she" (Logarithmic scale)',
       y = 'Relative uses after "she" to after "he"',
       title = "Gendered Reporting: Pre Weinstein, The Guardian",
       subtitle = "Words occurring at least 10 times after he/she:
                  160 unique words (100 displayed) | 11,013 occurrences in total") +
  expand_limits(y = c(4, -4)) +
  theme_void()
```

### Emotional Range 
```{r}
# get sentiments lexicon
afinn <- get_sentiments("afinn")    
words <- words %>%
  inner_join(afinn)

# loop over rows to add up score 
x = 0
for (i in seq(1:502)) {
  words$tot[i] <- words$score[i] + x
  x =  words$tot[i]
}

# reset index 
words <- words %>% 
  mutate(row = row_number())

# create order to chapters

words$chapter_txt <- ifelse(words$chapter == "Intuition", "1. Intuition", words$chapter)
words$chapter_txt <- ifelse(words$chapter == "Denial", "2. Denial", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Anger", "3. Anger", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Apathy", "4. Apathy", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Emptiness", "5. Emptiness", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Accountability", "6. Accountability", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Reformation", "7. Reformation", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Forgiveness", "8. Forgiveness", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Ressurection", "9. Ressurection", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Hope", "10. Hope", words$chapter_txt)
words$chapter_txt <- ifelse(words$chapter == "Redemption", "11. Redemption", words$chapter_txt)
words$chapter_txt <- factor(words$chapter_txt, levels = c("1. Intuition", "2. Denial", "3. Anger", "4. Apathy", "5. Emptiness", "6. Accountability", "7. Reformation", "8. Forgiveness", "9. Ressurection", "10. Hope", "11. Redemption"))

words <- filter(words, !is.na(words$chapter))
words$chapter <- factor(words$chapter, levels = c("Intuition", "Denial", "Anger", "Apathy", "Emptiness", "Accountability", "Reformation", "Forgiveness", "Ressurection", "Hope", "Redemption"))


# over time visualization
ggplot(data = words, aes(x = row, y = tot)) +
  geom_area(aes(fill = chapter_txt), alpha = 0.9, color = "white") +
  # scale_fill_manual(values=c("#ffff80","#ffff33", "#FFA500","#FF8C00", "#FF6126", "#FF4500", "#ffff66", "#ffff80", "#FF8C00", "#FF6347"), name = "Chapter") +
    scale_fill_manual(values=c("#ffff80","#ffff33", "#FFA500","#FF8C00", "#FF6126", "#FF4500", "#FF6347", "#FF8C00", "#ffca50", "#ffdb66", "#ff8172"), name = "Chapter") +
  labs(x = '', y = '', title = 'Lemonade: Emotional Range of Chapters Over Time\n', subtitle = '') +
  ggplot2::annotate(geom = "text", x = 5, y = 100, 
                    label = "Positive Words", size = 3, hjust = -0.1, vjust = -.1) +
  ggplot2::annotate("text", x = 5, y = 80, 
                    label = "Negative Words",  
                    size = 3, hjust = -0.1, vjust = -.1) +
    ggplot2::annotate("text", x = 200, y = 150, 
                    label = "Album Chapters",  
                    size = 3, hjust = -0.1, vjust = -.1) +
   #  ggplot2::annotate("text", x = -5, y = 8, 
   #                  label = "Intuition",  
   #                  size = 2.5, hjust = -0.1, vjust = -.1) +
   # ggplot2::annotate("text", x = 50, y = 8, 
   #                  label = "Denial",  
   #                  size = 2.5, hjust = -0.1, vjust = -.1) +
        geom_segment(aes(x = 0, xend = 0 , y = 100, yend = 130),
                     arrow = arrow(length = unit(0.2,"cm")), color = "#99ff33") +
        geom_segment(aes(x = 0, xend = 0 , y = 80, yend = 50),
                     arrow = arrow(length = unit(0.2,"cm")), color = "#F8766D") +
        geom_segment(aes(x = 270, xend = 315 , y = 152, yend = 152),
                     arrow = arrow(length = unit(0.2,"cm")), color = "gray") +
  theme_void() +
  theme(axis.text = element_blank(), 
        axis.ticks = element_blank(),
        legend.position = "top")


```

## Chapter 2: Denial 
```{r}
nrc_denial <- get_sentiments("nrc") %>% 
  filter(sentiment == "sadness"|sentiment == "negative")

denial <- doc_td %>%
  filter(Chapter == "Denial") %>%
  inner_join(nrc_denial) %>%
  count(word, sort = TRUE)


wordcloud(words = denial$word, freq = denial$n, max.words = 15, 
                  random.order = FALSE, rot.per = 0.35, colors = brewer.pal(2, "Dark2"))
```

## Chapter 3: Anger
```{r}
nrc_anger <- get_sentiments("nrc") %>% 
  filter(sentiment == "anger"| sentiment == "negative")

doc_td$word <- doc_td$term

anger <- doc_td %>%
  filter(Chapter == "Anger") %>%
  inner_join(nrc_anger) %>%
  count(word, sort = TRUE)

wordcloud(words = anger$word, freq = anger$n, max.words = 20, 
                  random.order = FALSE, rot.per = 0.35, colors = brewer.pal(2, "Dark2"))
```


